from __future__ import annotations

from app.skills.base import Skill, SkillContext, SkillResult


class GeneralBookPageSkill(Skill):
    skill_id = "general_book_page"
    name = "General book page"
    description = "Generates clear non-fiction and custom pages without domain-specific marketing bias"
    version = "1.0"

    async def run(self, input: dict, context: SkillContext) -> SkillResult:  # noqa: A003
        book = context.book
        goal = input.get("page_direction") or input.get("instruction") or "Develop the next section"
        rough = input.get("rough_text") or ""
        target_words = int(input.get("target_words") or 260)
        prompt = f"""
Book title: {book.title if book else 'Untitled'}
Genre or content direction: {book.genre if book else 'non-fiction'}
Book topic: {book.topic if book else ''}
Page direction: {goal}
Rough text: {rough}
Target words: {target_words}

Write reader-facing prose only.
No JSON or prompt labels.
Keep the writing practical, coherent, and informative.
Keep it concise enough to fit one visible page.
Do not repeat sentences to satisfy target words.
""".strip()
        text, notes = await context.llm_engine.generate_text(prompt, temperature=0.55)
        return SkillResult(
            output={
                "headline": None,
                "body_text": text,
                "pull_quote": None,
                "image_guidance": None,
                "layout_intent": "general_nonfiction",
                "source_refs": [],
                "quality_notes": ["Generated by general non-fiction skill."],
            },
            notes=notes,
        )
