from __future__ import annotations

from app.skills.base import Skill, SkillContext, SkillResult
from app.skills.writing_flow import maybe_run_two_pass_page_generation


class GeneralBookPageSkill(Skill):
    skill_id = "general_book_page"
    name = "General book page"
    description = "Generates clear non-fiction and custom pages without domain-specific marketing bias"
    version = "1.0"

    async def run(self, input: dict, context: SkillContext) -> SkillResult:  # noqa: A003
        book = context.book
        goal = input.get("page_direction") or input.get("instruction") or "Develop the next section"
        rough = input.get("rough_text") or ""
        target_words = int(input.get("target_words") or 260)
        text, notes, plan = await maybe_run_two_pass_page_generation(
            context=context,
            skill_kind="general",
            title=book.title if book else "Untitled",
            topic=book.topic if book else "",
            book_type=book.book_type_id if book else "general",
            previous_summary=(book.memory.global_summary if (book and book.memory) else ""),
            direction=goal,
            rough_notes=rough,
            source_excerpts=" ".join(chunk.text for chunk in (context.source_chunks or [])[:2]),
            target_words=target_words,
            composition=(context.page.layout_json or {}).get("composition", "text_only") if context.page else "text_only",
            audience=(context.project.audience if context.project else ""),
            objective=(context.project.objective if context.project else ""),
            domain_instructions=(
                "Write clear educational or explanatory non-fiction prose. "
                "No fictional scene unless explicitly requested. "
                "No marketing buzzword bias and no finance claim bias unless topic requires it."
            ),
            few_shot=(
                "Few-shot input: explain a concept for a practical guide.\n"
                "Output: clear section-style prose with topic, explanation, example, takeaway."
            ),
            strict_quality=bool(input.get("strict_quality")),
        )
        return SkillResult(
            output={
                "headline": None,
                "body_text": text,
                "pull_quote": None,
                "image_guidance": None,
                "layout_intent": "general_nonfiction",
                "source_refs": [],
                "quality_notes": ["Generated by general non-fiction skill."],
                "plan_summary": plan,
            },
            notes=notes,
        )
